Algoritmo "operacoesBasicasFacul"
Var
   x, y: real

Inicio
      Escreva("Entre com o valor 1: ")
      leia(x)
      Escreva("Entre com o valor 2: ")
      leia(y)

      Escreval("===========================================")
      Escreval("A soma dos valores e: ", x + y)
      Escreval("A subtracao dos valores e: ", x - y)
      Escreval("A multiplicao dos valores e: ", x * y)
      Escreval("A divisao dos valores e: ", x / y)


Fimalgoritmo