Algoritmo "positivonegativoouzero"

Var
   n: inteiro


Inicio
       escreva("Digite um valor: ")
       leia(n)
       
       Se (n < 0) entao
          Escreva("O valor digitado e negativo")
       senao
            Se (n > 0) entao
               Escreva("O valor digitado e positivo")
            senao
                 Se (n = 0) entao
                    Escreva("O valor digitado e ZERO")
                 fimse
            fimse
       fimse


Fimalgoritmo